name: ğŸ“Œ Security Issue
description: Create a Security issue
title: "security: "
labels: ["security"]

body:
  - type: textarea
    id: description
    attributes:
      label: ğŸ“„ Issue Description
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: ğŸ”„ Context / Steps
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: âœ… Expected Outcome
    validations:
      required: false

  - type: textarea
    id: actual
    attributes:
      label: âŒ Actual Outcome
    validations:
      required: false