name: Add PR Reaction

on:
  pull_request:
    types: [opened]

jobs:
  react:
    runs-on: ubuntu-latest

    steps:
      - name: Add Reaction on PR
        env:
          GH_TOKEN: ${{ secrets.MOHIT_GH_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}

          curl -X POST \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/reactions \
            -d '{"content":"eyes"}'